version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartdoor

  mongo:
    image: mongo
    ports:
      - "27017:27017"
